---
- name: change resolv.conf file
  hosts: all
  tasks:
        - name: nameserver and domain
          copy:
              src: /opt/mhdd-automation/resolv-file/resolv.conf
              dest: /etc/resolv.conf
              owner: root
              group: root
              mode: "0644"
              