---
 - name: Firewalld rules
   hosts: all
   vars_files:
        - /opt/mhdd-automation/ansible-inventory/node_vars.yml
   tasks:
    - name: Firewalld rules
      firewalld:
        permanent: yes
        immediate: yes
        port: "{{item.port}}/{{item.proto}}"
        state: "{{item.state}}"
        zone: "{{item.zone}}"
      with_items:
       - {port: "3306", proto: "tcp", state: "enabled", zone: "public" }
       - {port: "3307", proto: "tcp", state: "enabled", zone: "public" }
       - {port: "4567", proto: "tcp", state: "enabled", zone: "public" }
       - {port: "4568", proto: "tcp", state: "enabled", zone: "public" }
       - {port: "4444", proto: "tcp", state: "enabled", zone: "public" }
       - {port: "4567", proto: "udp", state: "enabled", zone: "public" }

    - name: add haproxy nodes 
      command: "{{ item }}"
      with_items:
            - "firewall-cmd --add-source {{ haproxy-node1 }} --permanent"
            - "firewall-cmd --add-source {{ haproxy-node2 }} --permanent"
            - "firewall-cmd --reload"

    - name: mariadb
      firewalld:
              name: mysql
              permanent: yes
              immediate: yes
              state: enabled

    - name: dns rule
      firewalld:
              name: dns
              permanent: yes
              immediate: yes
              state: enabled

