---
- name: update & upgrade nodes and install packages
  hosts: all
  tasks:
        - name: update & upgrade packages
          command: "yum update -y && yum upgrade -y"

        - name: Install essential software
          yum: name={{ item }} state=latest
          tags: software
          with_items:
                  - chrony
                  - psycopg2-binary
                  - bzip2
                  - zip
                  - unzip
                  - openssl-devel
                  - mc
                  - vim
                  - atop
                  - wget
                  - mytop
                  - screen
                  - net-tools
                  - rsync
                  - psmisc
                  - gdb
                  - subversion
                  - htop
                  - bind
                  - bind-utils
                  - sysstat
                  - nano
                  - iptraf
                  - ifdata
                  - nethogs
                  - ngrep
                  - tcpdump
                  - lm_sensors
                  - mtr
                  - s3cmd
                  - psmisc
                  - gcc
                  - git
                  - python3-pip
                  - python-devel
                  - epel-release
                  - yum-utils
                  - vim
                  - initscripts
                  - lvm2

        - name: install the 'Development tools' package group
          yum:
              name: "@Development tools"
              state: present   

        - name: install mariadb galera, rsync and selinux policy
          yum:
              name: "{{ item }}"
              state: latest
          with_items:
                  - mariadb-server-galera
                  - rsync
                  - python3-policycoreutils
          when: 
              - ansible_host == "node-1.server.local"
              - ansible_host == "node-2.server.local" 
                   
          