---
- name: create lvm partition
  hosts: all
  become: true
  gather_facts: false
  tasks:
        - name: create directory mount point
          file:
              state: directory
              path: /opt/data/bricks/glusterfs
              mode: "0755"

        - name: create vg
          lvg:
              vg: vgdata
              pvs: /dev/sdb

        - name: create lvm
          lvol:
              vg: vgdata
              lv: lvdata
              size: 100%FREE

        - name: create filesystem
          filesystem:
                    fstype: ext4
                    dev: /dev/vgdata/lvdata

        - name: mount partition
          mount:
                fstype: ext4
                src: /dev/vgdata/lvdata
                path: /opt/data/bricks/glusterfs
                state: mounted